#!/usr/bin/env bash
# displays numbers 1 through 20 with iterations.

i=1
while [ $i -lt 21 ]
do
case $i in

4)
echo $i
echo "bad luck from China"
;;

9)
echo $i
echo "bad luck from Japan"
;;

17)
echo $i
echo "bad luck from Italy"
;;
esac

((i+=1))
done
