#!/usr/bin/env bash
# manages manage_my_process script.

argv1=$1
start() {
	./manage_my_process & echo $! > "/var/run/my_process.pid" && echo "manage_my_process started"
}

stop() {
	sudo pkill -f "./manage-my_process" && sudo rm "/var/run/my_process.pid" && echo "manage_my_process stopped"
}

case "$argv1" in
	start) start
		;;

	stop) stop|
		;;

restart) restart
	;;

*) echo "Usage: manage_my_process {start|stop|restart}"
	;;

esac
